;;; Compiled snippets and support files for `org-mode'
;;; Snippet definitions:
;;;
(yas-define-snippets 'org-mode
                     '(("inv" "* $1\n\n** I. Location\n\n*** i. Geographical area\n\n*** ii. Region\n\n*** iii. Site\n\n** II. Name\n\n*** i. Full name (orig. language)\n\n*** ii. Full name (transliterated)\n\n** III. Date\n\n*** Date(s)\n\n** IV. Name and Terminology\n\n*** i. Name in other forms\n\n*** ii. Name elements\nTerms in transliteration\n\nList: \n- cultic\n- ethnic\n- geographical\n- heroic\n- kinship-related\n- personal\n- professional\n- status-related\n- theophoric\n- topographical\n- other\n\n*** iii. Descriptive terms\nE.g.: Koinon, eranos, synodos, thiasos (not just in the name)\n\n** V. Sources\n\n*** i. Source(s)\nRemember date.\nLine numbers if long inscriptions.\n\n**** a. Source type(s)\n\n**** b. Document(s) typology\n\n**** c. Physical format(s)\n\n*** ii. Source(s) provenance\n\n** VI. Built and Visual Place\n\n*** i. Archaeological remains\n\n*** ii. References to buildings/objects\n\n** VII. Organization\n\n*** i. Founder(s)\n\n*** ii. Leadership\n\n*** iii. Members\n\n*** iv. Officials\n\n*** v. Other staff\n\n*** vi. Laws and rules\n\n*** vii. Judicial system\n\n*** viii. Obligations\n\n*** ix. Privileges\n\n** VIII. Property and Possessions\n\n*** i. Trasury/funds\n\n*** ii. Realty\n\n*** iii. Income\n\n*** iv. Endowments\n\n** IX. Membership\n\n*** i. Number\n\n*** ii. Gender\n\n*** iii. Age\n\n*** iv. Status\n\n*** v. Relations\n\n** X. Activities\n\n*** i. Assemblies\n\n*** ii. Meetings & Events\n\n*** iii. Worship\n\n*** iv. Honours/other activities\n\n** XI. Interaction\n\n*** i. Local interaction\n\n*** ii. Interaction abroad\n\n** XII. Notes\n\n*** i. Comments\n\n*** ii. Poland concordance\n\n*** iii. Bibliography\n\n** XIII. Evalutaion\n\n*** i. Private association\n\n*** ii. Historical authenticity\n" "Inventory notes (complete)" nil nil nil "/Users/michael/emacs/snippets/custom/org-mode/Inventory notes (complete)" nil nil)
                       ("invb" "** $1${2:\n*** II. Name\n${3: **** i. Full name (orig. language)\n${4: note}}\n${5: **** ii. Full name (transliterated)\n${6: note}}}${7:\n*** XIII. Evaluation\n${8: **** i. Private association\n${9: note}}\n${10:**** ii. Historical authenticity\n${11: note}}}\n$0\n" "Inventory note (basic)" nil nil nil "/Users/michael/emacs/snippets/custom/org-mode/Inventory note (basic)" nil nil)
                       ("fl3" "\n*** $1: :drill:\n    \n    $1\n\n**** Oversættelse:\n     \n     $2" "Flash, level 3" nil nil nil "/Users/michael/emacs/snippets/custom/org-mode/Flash, level 3" nil nil)
                       ("quote" "#+BEGIN_QUOTE\n	$1 \n#+END_QUOTE\n$0" "Block quote" nil nil nil "/Users/michael/emacs/snippets/custom/org-mode/Block quote" nil nil)))


;;; Do not edit! File generated at Wed Jan 27 11:20:25 2016
