;;; Compiled snippets and support files for `latex-mode'
;;; Snippet definitions:
;;;
(yas-define-snippets 'latex-mode
                     '(("artcl" "\n\\documentclass[a4paper,11pt]{scrartcl}\n\n% Indstilling af xelatex\n\\usepackage{fontspec} \n\\usepackage{url}\n\\usepackage[no-sscript]{xltxtra}\n\\usepackage{paralist}\n\\usepackage{amsmath}\n\\usepackage[bottom]{footmisc}\n\n\n\\newcommand*\\myfont{Brill}\n\\setmainfont[Mapping=tex-text, Numbers=OldStyle]{\\myfont}\n\n\\usepackage{polyglossia}\n\\setmainlanguage{danish}\n\\setotherlanguages{greek,latin}\n\\setkeys{variant=ancient}\n\\newfontfamily\\greekfont[Script=Greek]{\\myfont}\n\n% Biblatex\n\\usepackage[bibstyle=authoryear, citestyle=authoryear-icomp, usetranslator=true, url=false, isbn=false, firstinits=true]{biblatex}\n%\\usepackage[bibstyle=draft, citestyle=draft, usetranslator=true, url=false, isbn=false, firstinits=true]{biblatex}\n\\DefineBibliographyStrings{danish}{%\n	references={Bibliografi},\n	editor={ed.},\n	editors={eds.},\n	in={in: },\n	andothers={et al.},\n	page={},\n	pages={},\n}\n\\bibliography{/Users/Michael/Documents/Filologi/Litteratur/Databaser/litteratur}\n\\renewcommand*{\\postnotedelim}{\\addcolon }\n\\renewcommand*{\\bibpagespunct}{\\addcolon }\n\\AtEveryBibitem{%\n  \\clearfield{day}%\n  \\clearfield{month}%\n  \\clearfield{endday}%\n  \\clearfield{endmonth}%\n}\n\n\n% Titel\n\\newcommand*\\mytitle{$1}\n\\newcommand*\\mydate{\\today}\n\n% Headers og footers\n\\usepackage{fancyhdr}\n\\setlength{\\headheight}{12.5pt}\n \n\\pagestyle{fancyplain}\n \n\\lhead{\\mytitle}\n\\chead{}\n\\rhead{Michael S. Christensen}\n\\lfoot{}\n\\cfoot{\\thepage}\n\\rfoot{}\n\n\n\\title{\\mytitle}\n\\author{Michael Stenskjær Christensen}\n\\date{\\mydate}\n\n\n\\begin{document}\n$0\n\n\n\\end{document}" "scrartcl document" nil nil nil "/Users/Michael-macbook/.emacs.d/private/snippets/latex-mode/scrartcl document" nil nil)
                       ("oldcite" "\\old$1cite${2:[${3:ref}]}{${4:arist.DA}}" "oldcite" nil nil nil "/Users/Michael-macbook/.emacs.d/private/snippets/latex-mode/oldcite" nil nil)
                       ("gl" "\\newglossaryentry{${1:AC}}\n{\nname=${2:Andrea Crotti}${3:,\nplural=${4:plural}}${5:,\ndescription=${6:description}}\n}" "newglossaryentry" nil nil nil "/Users/Michael-macbook/.emacs.d/private/snippets/latex-mode/newglossaryentry" nil nil)
                       ("=" "\\={$1}$0" "latex macron" nil nil nil "/Users/Michael-macbook/.emacs.d/private/snippets/latex-mode/latex macron" nil nil)
                       ("fn" "\\footnote{$1}$0" "footnote" nil nil nil "/Users/Michael-macbook/.emacs.d/private/snippets/latex-mode/footnote" nil nil)
                       ("letter" "\n\\documentclass[DINmtext, pagenumber=footright, parskip=half-,%\n                fromalign=left, fromphone=true,%\n                fromemail=true, fromurl=false, %\n                fromlogo=false, fromrule=false, %\n                firsthead=false, addrfield=true, %\n                backaddress=true, 12pt] {scrlttr2}\n\n\\usepackage[latin1]{inputenc}\n\\usepackage{polyglossia}\n\\setmainlanguage{$1}\n\\usepackage{fontenc}\n\n\n\\pagestyle{plain}\n\n\\setkomavar{fromname}{Michael S. Christensen}\n\\setkomavar{fromaddress}{Bisiddervej 33, 3. th}\n\\setkomavar{fromzipcode}{2400 København S}\n\\setkomavar{fromemail}{michaelsc@hum.ku.dk}\n\\setkomavar{signature}{Michael Stenskjær Christensen}\n\\setkomavar{subject}{$2}\n\n\n\\date{$3, \\today}\n\\begin{document}\n\\begin{letter}{Adresse}\n\n\n\\opening{Kære $4}\n\n$0\n\n\\closing{Closing}\n\n\\encl{Evt. vedlæg}\n\n\n\\end{letter}\n\\end{document}\n" "Koma-letter" nil nil nil "/Users/Michael-macbook/.emacs.d/private/snippets/latex-mode/Koma-letter" nil nil)
                       ("fnc" "\\edtext{$1}{\\Cfootnote{$2}} $0" "Footnote C" nil nil nil "/Users/Michael-macbook/.emacs.d/private/snippets/latex-mode/Footnote C" nil nil)
                       ("fnb" "\\edtext{$1}{\\Bfootnote{$2}} $0" "Footnote b" nil nil nil "/Users/Michael-macbook/.emacs.d/private/snippets/latex-mode/Footnote B" nil nil)
                       ("fna" "\\edtext{$1}{\\Afootnote{$2}} $0" "Footnote A" nil nil nil "/Users/Michael-macbook/.emacs.d/private/snippets/latex-mode/Footnote A" nil nil)))


;;; Do not edit! File generated at Mon Aug 14 15:27:46 2017
