;;; Compiled snippets and support files for `latex-mode'
;;; Snippet definitions:
;;;
(yas-define-snippets 'latex-mode
                     '(("pkg" "\\usepackage{$0}" "usepackage" nil nil nil "/Users/michael/emacs/snippets/standard/latex-mode/usepackage" nil nil)
                       ("b" "\\textbf{$1}$0" "textbf" nil nil nil "/Users/michael/emacs/snippets/standard/latex-mode/textbf" nil nil)
                       ("sub" "\\subsection{${1:name}}\n\\label{subsec:${2:label}}\n\n$0" "subsec" nil nil nil "/Users/michael/emacs/snippets/standard/latex-mode/subsec" nil nil)
                       ("subfig" "\\begin{figure}[ht]\n  \\centering\n  \\subfigure[$1]\n  {\\label{fig:${2:label}} \n    \\includegraphics[width=.${3:5}\\textwidth]{${4:path}}}\n\n  \\caption{${5:caption}}\n\\label{fig:${6:label}}\n\\end{figure}\n" "subfigure" nil nil nil "/Users/michael/emacs/snippets/standard/latex-mode/subfigure" nil nil)
                       ("sf" "\\subfigure[${1:caption}]{\n  \\label{fig:${2:label}} \n  \\includegraphics[width=.${3:3}\\textwidth]{${4:path}}}\n$0" "subf" nil nil nil "/Users/michael/emacs/snippets/standard/latex-mode/subf" nil nil)
                       ("sec" "\\section{${1:name}}\n\\label{sec:${2:label}}\n\n$0" "section" nil nil nil "/Users/michael/emacs/snippets/standard/latex-mode/section" nil nil)
                       ("artcl" "\n\\documentclass[a4paper,11pt]{scrartcl}\n\n% Indstilling af xelatex\n\\usepackage{xltxtra}\n\\usepackage[bottom]{footmisc}\n\n\\newcommand*\\myfont{Brill}\n\\setmainfont[Mapping=tex-text, Numbers=OldStyle]{\\myfont}\n\\usepackage{microtype}\n\n\\usepackage{polyglossia}\n\\setmainlanguage{danish}\n\\setotherlanguages{greek,latin}\n\n% Biblatex\n\\usepackage[bibstyle=authoryear, citestyle=authoryear-icomp, usetranslator=true, url=false, isbn=false, firstinits=true]{biblatex}\n\\DefineBibliographyStrings{danish}{%\n	references={Bibliografi},\n	editor={ed.},\n	editors={eds.},\n	in={in: },\n	andothers={et al.},\n	page={},\n	pages={},\n}\n\\bibliography{litteratur}\n\\renewcommand*{\\postnotedelim}{\\addcolon }\n\\renewcommand*{\\bibpagespunct}{\\addcolon }\n\\AtEveryBibitem{%\n  \\clearfield{day}%\n  \\clearfield{month}%\n  \\clearfield{endday}%\n  \\clearfield{endmonth}%\n}\n\n\n% Titel\n\\newcommand*\\mytitle{$1}\n\\newcommand*\\mydate{\\today}\n\n% Headers og footers\n\\usepackage{fancyhdr}\n\\setlength{\\headheight}{12.5pt}\n \n\\pagestyle{fancyplain}\n \n\\lhead{\\mytitle}\n\\chead{}\n\\rhead{Michael S. Christensen}\n\\lfoot{}\n\\cfoot{\\thepage}\n\\rfoot{}\n\n\n\\title{\\mytitle}\n\\author{Michael Stenskjær Christensen}\n\\date{\\mydate}\n\n\n\\begin{document}\n$0\n\n\n\\end{document}" "scrartcl document" nil nil nil "/Users/michael/emacs/snippets/standard/latex-mode/scrartcl document" nil nil)
                       ("q" "\\question{$0}" "question" nil nil nil "/Users/michael/emacs/snippets/standard/latex-mode/question" nil nil)
                       ("py" "\\lstset{language=python}\n\\begin[language=python]{lstlisting}\n$0\n\\end{lstlisting}" "python" nil nil nil "/Users/michael/emacs/snippets/standard/latex-mode/python" nil nil)
                       ("no" "\\note{$0}" "note" nil nil nil "/Users/michael/emacs/snippets/standard/latex-mode/note" nil nil)
                       ("gl" "\\newglossaryentry{${1:AC}}{name=${2:Andrea Crotti}${3:, description=${4:description}}}" "newglossaryentry" nil nil nil "/Users/michael/emacs/snippets/standard/latex-mode/newglossaryentry" nil nil)
                       ("cmd" "\\newcommand{\\\\${1:name}}${2:[${3:0}]}{$0}" "newcommand" nil nil nil "/Users/michael/emacs/snippets/standard/latex-mode/newcommand" nil nil)
                       ("movie" "\\begin{center}\n\\includemovie[\n  label=test,\n  controls=false,\n  text={\\includegraphics[width=4in]{${1:image.pdf}}}\n]{4in}{4in}{${2:video file}}\n\n\\movieref[rate=3]{test}{Play Fast}\n\\movieref[rate=1]{test}{Play Normal Speed} \n\\movieref[rate=0.2]{test}{Play Slow}\n\\movieref[resume]{test}{Pause/Resume}\n" "movie" nil nil nil "/Users/michael/emacs/snippets/standard/latex-mode/movie" nil nil)
                       ("lst" "\\begin{lstlisting}[float,label=lst:${1:label},caption=nextHopInfo: ${2:caption}]\n$0\n\\end{lstlisting}" "listing" nil nil nil "/Users/michael/emacs/snippets/standard/latex-mode/listing" nil nil)
                       ("lab" "\\label{$0}" "label" nil nil nil "/Users/michael/emacs/snippets/standard/latex-mode/label" nil nil)
                       ("it" "\\begin{itemize}\n$0\n\\end{itemize}" "itemize" nil nil nil "/Users/michael/emacs/snippets/standard/latex-mode/itemize" nil nil)
                       ("-" "\\item $0" "item" nil nil nil "/Users/michael/emacs/snippets/standard/latex-mode/item" nil nil)
                       ("ig" "\\includegraphics${1:[$2]}{$0}" "includegraphics" nil nil nil "/Users/michael/emacs/snippets/standard/latex-mode/includegraphics" nil nil)
                       ("if" "\\IF {$${1:cond}$}\n    $0\n\\ELSE\n\\ENDIF \n" "if" nil nil nil "/Users/michael/emacs/snippets/standard/latex-mode/if" nil nil)
                       ("gp" "\\glspl{${1:label}}" "glspl" nil nil nil "/Users/michael/emacs/snippets/standard/latex-mode/glspl" nil nil)
                       ("g" "\\gls{${1:label}}" "gls" nil nil nil "/Users/michael/emacs/snippets/standard/latex-mode/gls" nil nil)
                       ("fr" "\\begin{frame}\n        \\frametitle{$1}\n        $0\n\\end{frame}" "frame" nil nil nil "/Users/michael/emacs/snippets/standard/latex-mode/frame" nil nil)
                       ("fig" "\\begin{figure}[ht]\n  \\centering\n  \\includegraphics[${1:options}]{figures/${2:path.pdf}}\n  \\caption{\\label{fig:${3:label}} $0}\n\\end{figure}\n" "figure" nil nil nil "/Users/michael/emacs/snippets/standard/latex-mode/figure" nil nil)
                       ("e" "\\emph{$1}$0" "emph" nil nil nil "/Users/michael/emacs/snippets/standard/latex-mode/emph" nil nil)
                       ("cols" "\\begin{columns}\n  \\begin{column}{.${1:5}\\textwidth}\n  $0\n  \\end{column}\n\n  \\begin{column}{.${2:5}\\textwidth}\n\n  \\end{column}\n\\end{columns}" "columns" nil nil nil "/Users/michael/emacs/snippets/standard/latex-mode/columns" nil nil)
                       ("code" "\\begin{lstlisting}\n$0\n\\end{lstlisting}" "code" nil nil nil "/Users/michael/emacs/snippets/standard/latex-mode/code" nil nil)
                       ("c" "\\cite{$1} $0" "cite" nil nil nil "/Users/michael/emacs/snippets/standard/latex-mode/cite" nil nil)
                       ("ca" "\\caption{$0}" "caption" nil nil nil "/Users/michael/emacs/snippets/standard/latex-mode/caption" nil nil)
                       ("G" "\\Gls{${1:label}}" "Gls" nil nil nil "/Users/michael/emacs/snippets/standard/latex-mode/capgls" nil nil)
                       ("bl" "\\begin{block}{$1}\n        $0\n\\end{block}" "block" nil nil nil "/Users/michael/emacs/snippets/standard/latex-mode/block" nil nil)
                       ("alg" "\\begin{algorithmic}\n$0\n\\end{algorithmic}\n" "alg" nil nil nil "/Users/michael/emacs/snippets/standard/latex-mode/alg" nil nil)
                       ("al" "\\begin{alertblock}{$2}\n        $0\n\\end{alertblock}" "alertblock" nil nil nil "/Users/michael/emacs/snippets/standard/latex-mode/alertblock" nil nil)
                       ("ac" "\\newacronym{${1:label}}{${1:$(upcase yas-text)}}{${2:Name}}" "acronym" nil nil nil "/Users/michael/emacs/snippets/standard/latex-mode/acronym" nil nil)
                       ("oldtitle" "\\old[title]{$1}$0" "Old reference, title" nil nil nil "/Users/michael/emacs/snippets/standard/latex-mode/Old reference, title" nil nil)
                       ("old" "\\old${1:*}${2:[]}{$3}{$4}{$5}{$6}$0" "Old reference" nil nil nil "/Users/michael/emacs/snippets/standard/latex-mode/Old reference" nil nil)
                       ("oldfn" "\\footnote{\\old${1:*}${2:[]}{$3}{$4}{$5}{$6}$0}" "Old cite footnote" nil nil nil "/Users/michael/emacs/snippets/standard/latex-mode/Old cite footnote" nil nil)
                       ("newcmd" "\n% $1\n\\NewDocumentCommand {\\\\${2:name}} ${3:{$4}} {%\n  $0\n}\n" "NewDocumentCommand" nil nil nil "/Users/michael/emacs/snippets/standard/latex-mode/NewDocumentCommand" nil nil)
                       ("rerum" "\\rerum${1:[]}{$2}${3:{}}$0" "Index rerum" nil nil nil "/Users/michael/emacs/snippets/standard/latex-mode/Index rerum" nil nil)
                       ("dyder" "\\dyder{$1}${2:{}}$0" "Index dyder" nil nil nil "/Users/michael/emacs/snippets/standard/latex-mode/Index dyder" nil nil)
                       ("fn" "\\footnote{$1}$0" "Footnote" nil nil nil "/Users/michael/emacs/snippets/standard/latex-mode/Footnote" nil nil)
                       ("af" "\\Afootnote{$0}" "Afootnote" nil nil nil "/Users/michael/emacs/snippets/standard/latex-mode/Afootnote" nil nil)))


;;; Do not edit! File generated at Wed Jan 27 11:20:25 2016
